"""Add message reactions and replies

Revision ID: 3408e24f3353
Revises: 006b82f7579b
Create Date: 2026-01-20 11:56:51.403706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3408e24f3353'
down_revision: Union[str, None] = '006b82f7579b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    notification_type = postgresql.ENUM('FOLLOW', 'LIKE', 'COMMENT', 'MENTION', 'MESSAGE', 'SYSTEM', 'AI', name='notificationtype')
    notification_type.create(op.get_bind())

    op.drop_index(op.f('idx_like_post_id'), table_name='likes')
    op.drop_index(op.f('idx_like_user_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_index(op.f('idx_comment_created_at'), table_name='comments')
    op.drop_index(op.f('idx_comment_post_id'), table_name='comments')
    op.drop_index(op.f('idx_comment_user_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.add_column('messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('original_content', sa.Text(), nullable=True))
    op.create_index('idx_message_reply_to_id', 'messages', ['reply_to_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    
    # Now use the enum in alter_column
    # First drop the default to avoid casting issues with the default value
    op.alter_column('notifications', 'type', server_default=None)
    
    # Uppercase existing data to match Enum values
    op.execute("UPDATE notifications SET type = UPPER(type)")

    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FOLLOW', 'LIKE', 'COMMENT', 'MENTION', 'MESSAGE', 'SYSTEM', 'AI', name='notificationtype'),
               existing_nullable=False,
               postgresql_using="type::text::notificationtype")
               
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_posts_created_at'), table_name='posts')
    op.drop_index(op.f('idx_posts_user_id'), table_name='posts')
    op.drop_constraint(op.f('posts_user_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_user_id_fkey'), 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('idx_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    
    # Convert back to varchar
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('FOLLOW', 'LIKE', 'COMMENT', 'MENTION', 'MESSAGE', 'SYSTEM', 'AI', name='notificationtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="type::text")
    
    # Restore default
    op.alter_column('notifications', 'type', server_default=sa.text("'system'::character varying"))
               
    # Drop the enum type after reverting column
    notification_type = postgresql.ENUM('FOLLOW', 'LIKE', 'COMMENT', 'MENTION', 'MESSAGE', 'SYSTEM', 'AI', name='notificationtype')
    notification_type.drop(op.get_bind())

    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('idx_message_reply_to_id', table_name='messages')
    op.drop_column('messages', 'original_content')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'reply_to_id')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('device_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('comments_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('comments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('idx_comment_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('idx_comment_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('idx_comment_created_at'), 'comments', ['created_at'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('likes_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('likes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('likes_pkey')),
    sa.UniqueConstraint('user_id', 'post_id', name=op.f('uq_user_post_like'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_like_user_id'), 'likes', ['user_id'], unique=False)
    op.create_index(op.f('idx_like_post_id'), 'likes', ['post_id'], unique=False)
    # ### end Alembic commands ###
